### ISSUE TITLE
Indentation Inconsistencies in Example Code

### ISSUE THREAD

**Issue by gregmarra** [CrossTheRoadElec/Phoenix-Examples-Languages#10]
Several of the Java examples have inconsistent indentation. Since this is example code, it would be ideal to model best practices.

Examples include:
* L14 - L38 in https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/Java/MotionMagic/src/org/usfirst/frc/team217/robot/Instrum.java , which should be further indentend
* L39 - L60 in https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/Java/PositionClosedLoop/src/org/usfirst/frc/team217/robot/Robot.java , which should be further indented

**Comment by ozrien** [comment]
Should be better now.
