### ISSUE TITLE
Add example of reading WPI_TalonSRX limit switch state in Java

### ISSUE THREAD

**Issue by wdross** [CrossTheRoadElec/Phoenix-Examples-Languages#16]
In trying to understand what information is available to the Java object, it appears not possible (or is it a matter of dereferencing the correct property?) to read the state of a WPI_TalonSRX limit switch.  
Something like the IsFwdLimitSwitchClosed() method that appears to be part of the MotControllerJNI class.

**Comment by ozrien** [comment]
You can read the limit switch of a Talon SRX, regardless of whether its a WPI_ object or not.
https://github.com/CrossTheRoadElec/Phoenix-Documentation#limit-switch-as-digital-inputs

API Doc here...
http://www.ctr-electronics.com/downloads/api/java/html/com/ctre/phoenix/motorcontrol/SensorCollection.html#isFwdLimitSwitchClosed--

**Comment by ozrien** [comment]
Also C++ example here, Java is very similar.
https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/a1932738a9ee44097106a7d036ee4ba36d9fe9b6/C%2B%2B/LimitSwitch/src/Robot.cpp

**Comment by wdross** [comment]
Thank you!
