### ISSUE TITLE
Canifier I2C

### ISSUE THREAD

**Issue by RKouchoo** [CrossTheRoadElec/Phoenix-Examples-Languages#19]
Does the canifier support I2C yet?
Is there demo code available?

Thanks.

**Comment by JCaporuscio** [comment]
CANifier does not yet support I2C.  This will likely be added in the off-season.

**Comment by witcpalek** [comment]
@JCaporuscio Did support for I2C get added?  The documentation doesn't seem to have been updated (lists it as a future feature, but the date is 2017).  APIs, doesn't have to have added it either.  Just want to confirm because we have color sensors that we'd like to put on the CAN bus.  Thanks.

**Comment by witcpalek** [comment]
@JCaporuscio thanks for the quick response
