### ISSUE TITLE
Did Constants.kPigeonUnitsPerRotation move to somewhere else?

### ISSUE THREAD

**Issue by Grantham00** [CrossTheRoadElec/Phoenix-Examples-Languages#42]
I was following HERO C# DriveStraightAuxiliary[Pigeon] example. However it does not find Constants.kPigeonUnitsPerRotation. Peeking constants definition, it's nowhere in there. Did it move to somewhere else?

I saw looking through the commit history that it was 8192, so I think I can just use that number for now?

**Comment by JCaporuscio** [comment]
kPigeonUnitsPerRotation is still in the constants file: https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/HERO%20C%23/DriveStraightAuxiliary%5BPigeon%5D/Platform/Platform.cs#L22

Did you download the examples recently?  Or import a constants file from a different example?

**Comment by Grantham00** [comment]
Oh noooo I did!

Thank you for your quick response and your help. And thank you for maintaining this wonderful platform!
