### ISSUE TITLE
Simulation Examples (WPILIB 2021)

### ISSUE THREAD

**Issue by dawonn** [CrossTheRoadElec/Phoenix-Examples-Languages#49]
Are there any examples for how t use the simulation interfaces? How do I set position and rate of the simulated device (Example)?

**Comment by bhall-ctre** [comment]
Most examples that are capable of running Phoenix simulation have been updated to do so. For instance, our Motion Magic example works with simulated Talon SRX and Victor SPX devices.

You can find instructions for getting started with Phoenix simulation using our examples in our [FRC 2021 Kickoff blog post](https://phoenix-documentation.readthedocs.io/en/latest/blog/blog-kickoff-2021.html#phoenix-simulation-examples).

**Comment by dawonn** [comment]
Yeah, that looks ideal thanks!
