### ISSUE TITLE
How to get the feedforward in Arbitrary Feed Forward

### ISSUE THREAD

**Issue by mendax1234** [CrossTheRoadElec/Phoenix-Examples-Languages#52]
It seems that the CTRE's feedforward is different from that in WPILIB. Does it have an kS, kV, kA? Besides , how to get the feedforward int Arbitrary Feed Forward?

**Comment by JCaporuscio** [comment]
So the "kF" term that is part of the PIDF constants is actually "kV" in practice.  There is no kS or kA term in the build-in PIDF constants, but you can use the arbitrary feed forward term if you're doing your closed-loop calculations on the RIO (ie, just sum together the results of your kS/kV/kA terms before passing them in).

Can you clarify you question regarding Arbitrary Feed Forward?
For reference: https://docs.ctre-phoenix.com/en/stable/ch16_ClosedLoop.html#arbitrary-feed-forward

**Comment by mendax1234** [comment]
Thanks, it seems that how to set Position in open loop ?
