### ISSUE TITLE
A question about the full ouput of TalonFX

### ISSUE THREAD

**Issue by mendax1234** [CrossTheRoadElec/Phoenix-Examples-Languages#53]
<img width="554" alt="屏幕截图 2021-11-27 140516" src="https://user-images.githubusercontent.com/62934294/143670170-a7089638-e17c-4587-bfab-64420769da67.png">
So , what is the full ouput of TalonFX , and what 's unit of it ?

**Comment by JCaporuscio** [comment]
The PID controller output is a scalar, so there's no units.  The comment above applies to all Talons, both SRX and FX.
1023 is full output and 0 is neutral.  The only place this is relevant is when using PID control.

**Comment by mendax1234** [comment]
Thanks a lot !

**Comment by mendax1234** [comment]
So , the kF is always the same in TalonFX and TalonSRX , since there full output is the same.
