### ISSUE TITLE
What is the max velocity of Falcon 500 (in 100ms)

### ISSUE THREAD

**Issue by mendax1234** [CrossTheRoadElec/Phoenix-Examples-Languages#54]
l want to use the max velocity to calculate my swerve's percentoutput. However, l don't know the accurate max velocity of Falcon 500.

**Comment by cpapplefamily** [comment]
I suggest looking at the sample velocity code. Run that code on your robot and use the Phoenix tunnel and console outputs the code pushes out to empirically measure the performance. 

@ozrien @JCaporuscio on lines 127 abs 132 of the falcon velocity closed loop it describes 500 rpm but the joystick conversion looks like 2000. It's been awhile since I too run that experiment above so I don't recall if that is a typo or a conversion

**Comment by JCaporuscio** [comment]
Yes, it's definitely using 2000 rpm as a target.  The comment is likely a copy-paste error from other velocity examples.

@mendax1234 The maximum velocity is going to depend on the load applied to the motor (see the motor curves [here](https://motors.vex.com/vexpro-motors/falcon)), meaning you're not going to be able to consistently calculate your percent output from velocity alone.

I would suggest just using [TalonFX.getMotorOutputPercent()](https://store.ctr-electronics.com/content/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_base_motor_controller.html#ab98555568a308792dd6f63d6a544d103) directly, that gives you what you're looking for.

**Comment by mendax1234** [comment]
`The maximum velocity is going to depend on the load applied to the motor (see the motor curves here), meaning you're not going to be able to consistently calculate your percent output from velocity alone.`

So , how to calculate the percentoutput if l want it to get to the same real speed as l set in velocity?

**Comment by cpapplefamily** [comment]
You don't want to command the motor with _talon.set(controlmode.petcentOutput, setpiont) but instead use _talon.set(Controlmode.Velocity, setpoint) look at the velocity sample. The CTRE samples are super. Most cases I have my students directly modify the sample  code to match our environment and load it onto our robot for testing on the target subsystem. I suspect your looking at a closed loop flywheel.
