### ISSUE TITLE
C++ sims not working in Talon FX directory

### ISSUE THREAD

**Issue by SpencerGreene** [CrossTheRoadElec/Phoenix-Examples-Languages#64]
To reproduce: open MotionMagic or DifferentialDrive project inside "C++ Talon FX (Falcon 500)", using VSCode WPILib 2023.1.1 release. Run "Simulate Robot Code".  Error message "Task 'simulateExternalJavaRelease' not found in root project 'MotionMagic'."

The simulations in the "C++ General" work fine (the two that I tried anyway).

From what I can tell, it's trying to run the java sim rather than the C++ sim - maybe something in the config was pasted from java? - but I can't figure out what it is.

**Comment by SpencerGreene** [comment]
Found the issue - should be fixed by https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/pull/65/

**Comment by CoryNessCTR** [comment]
Good catch! As I was updating the examples I copy-pasted everything starting from java and worked my way back to bring the C++ examples back up to date. I must've missed this portion for the Talon FX C++ examples. Thank you for the help!
